name: Pull Request CI

# Trigger when PR is created or updated
on:
  pull_request:
    branches:
      - main  # PR targeting "main" branch

jobs:
  build:
    runs-on: ubuntu-latest  # The virtual machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
